/*
===========================================================================
Data Structure Definition for Hospitality Data Schema
===========================================================================
This file contains all the meta information regarding the columns described in the CSV files. 5 CSV files have been provided.
1. dim_date
2. dim_hotels
3. dim_rooms
4. fact_aggregated_bookings
5. fact_bookings
	
*/

USE PortfolioProject;
GO

-- Create Schemas
CREATE SCHEMA hospitality;
GO


/*
1. hospitality.dim_date
	Column Description for dim_date:
		1. date: This column represents the dates present in May, June and July.
		2. mmm yy: This column represents the date in the format of mmm yy (monthname year).
		3. week no: This column represents the unique week number for that particular date.
		4. day_type: This column represents whether the given day is Weekend or Weekeday.
*/

IF OBJECT_ID ('hospitality.dim_date', 'U') IS NOT NULL
	DROP TABLE hospitality.dim_date;
CREATE TABLE hospitality.dim_date (
	date			DATE,
	mmm_yy			NVARCHAR(50),
	week_no			NVARCHAR(50),
	day_type		NVARCHAR(50)
);
GO


/*
2. hospitality.dim_hotels
	Column Description for dim_hotels:
		1. property_id: This column represents the Unique ID for each of the hotels.
		2. property_name: This column represents the name of each hotel.
		3. category: This column determines which class[Luxury, Business] a particular hotel/property belongs to. 
		4. city: This column represents where the particular hotel/property resides in.
*/

IF OBJECT_ID ('hospitality.dim_hotels', 'U') IS NOT NULL
	DROP TABLE hospitality.dim_hotels;
CREATE TABLE hospitality.dim_hotels (
	property_id			INT,
	property_name		NVARCHAR(50),
	category			NVARCHAR(50),
	city				NVARCHAR(50)
);
GO


/*
3. hospitality.dim_rooms
	Column Description for dim_rooms:
		1. room_id: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
		2. room_class: This column represents to which class[Standard, Elite, Premium, Presidential] particular room type belongs.
*/

IF OBJECT_ID ('hospitality.dim_rooms', 'U') IS NOT NULL
	DROP TABLE hospitality.dim_rooms;
CREATE TABLE hospitality.dim_rooms (
	room_id			NVARCHAR(10),
	room_class		NVARCHAR(50)
);
GO


/*
4. hospitality.fact_aggregated_bookings
	Column Description for fact_aggregated_bookings:
		1. property_id: This column represents the Unique ID for each of the hotels.
		2. check_in_date: This column represents all the check_in_dates of the customers.
		3. room_category: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
		4. successful_bookings: This column represents all the successful room bookings that happen for a particular room type in that hotel on that particular date.
		5. capacity: This column represents the maximum count of rooms available for a particular room type in that hotel on that particular date.
*/

IF OBJECT_ID ('hospitality.fact_aggregated_bookings', 'U') IS NOT NULL
	DROP TABLE hospitality.fact_aggregated_bookings;
CREATE TABLE hospitality.fact_aggregated_bookings (
	property_id				INT,
	check_in_date			DATE,
	room_category			NVARCHAR(10),
	successful_bookings		INT,
	capacity				INT
);
GO


/*
5. hospitality.fact_bookings
	Column Description for fact_bookings:
		1. booking_id: This column represents the Unique Booking ID for each customer when they booked their rooms.
		2. property_id: This column represents the Unique ID for each of the hotels
		3. booking_date: This column represents the date on which the customer booked their rooms.
		4. check_in_date: This column represents the date on which the customer check-in(entered) at the hotel.
		5. check_out_date: This column represents the date on which the customer check-out(left) of the hotel.
		6. no_guests: This column represents the number of guests who stayed in a particular room in that hotel.
		7. room_category: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
		8. booking_platform: This column represents in which way the customer booked his room.
		9. ratings_given: This column represents the ratings given by the customer for hotel services.
		10. booking_status: This column represents whether the customer cancelled his booking[Cancelled], successfully stayed in the hotel[Checked Out] or booked his room but not stayed in the hotel[No show].
		11. revenue_generated: This column represents the amount of money generated by the hotel from a particular customer.
		12. revenue_realized: This column represents the final amount of money that goes to the hotel based on booking status. If the booking status is cancelled, then 40% of the revenue generated is deducted and the remaining is refunded to the customer. If the booking status is Checked Out/No show, then full revenue generated will goes to hotels.
*/

IF OBJECT_ID ('hospitality.fact_bookings', 'U') IS NOT NULL
	DROP TABLE hospitality.fact_bookings;
CREATE TABLE hospitality.fact_bookings (
	booking_id				NVARCHAR(50),
	property_id				INT,
	booking_date			DATE,
	check_in_date			DATE,
	check_out_date			DATE,
	no_guests				INT,
	room_category			NVARCHAR(10),
	booking_platform		NVARCHAR(50),
	ratings_given			INT,
	booking_status			NVARCHAR(50),
	revenue_generated		INT,
	revenue_realized		INT
);
GO